// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authority_info.proto

package ca;

public final class AuthorityInfoOuterClass {
  private AuthorityInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AuthorityInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ca.AuthorityInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.aelf.Address contract_address = 1;</code>
     * @return Whether the contractAddress field is set.
     */
    boolean hasContractAddress();
    /**
     * <code>.aelf.Address contract_address = 1;</code>
     * @return The contractAddress.
     */
    aelf.Core.Address getContractAddress();
    /**
     * <code>.aelf.Address contract_address = 1;</code>
     */
    aelf.Core.AddressOrBuilder getContractAddressOrBuilder();

    /**
     * <code>.aelf.Address owner_address = 2;</code>
     * @return Whether the ownerAddress field is set.
     */
    boolean hasOwnerAddress();
    /**
     * <code>.aelf.Address owner_address = 2;</code>
     * @return The ownerAddress.
     */
    aelf.Core.Address getOwnerAddress();
    /**
     * <code>.aelf.Address owner_address = 2;</code>
     */
    aelf.Core.AddressOrBuilder getOwnerAddressOrBuilder();
  }
  /**
   * Protobuf type {@code ca.AuthorityInfo}
   */
  public  static final class AuthorityInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ca.AuthorityInfo)
      AuthorityInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AuthorityInfo.newBuilder() to construct.
    private AuthorityInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AuthorityInfo() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AuthorityInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AuthorityInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              aelf.Core.Address.Builder subBuilder = null;
              if (contractAddress_ != null) {
                subBuilder = contractAddress_.toBuilder();
              }
              contractAddress_ = input.readMessage(aelf.Core.Address.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(contractAddress_);
                contractAddress_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              aelf.Core.Address.Builder subBuilder = null;
              if (ownerAddress_ != null) {
                subBuilder = ownerAddress_.toBuilder();
              }
              ownerAddress_ = input.readMessage(aelf.Core.Address.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ownerAddress_);
                ownerAddress_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ca.AuthorityInfoOuterClass.internal_static_ca_AuthorityInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ca.AuthorityInfoOuterClass.internal_static_ca_AuthorityInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ca.AuthorityInfoOuterClass.AuthorityInfo.class, ca.AuthorityInfoOuterClass.AuthorityInfo.Builder.class);
    }

    public static final int CONTRACT_ADDRESS_FIELD_NUMBER = 1;
    private aelf.Core.Address contractAddress_;
    /**
     * <code>.aelf.Address contract_address = 1;</code>
     * @return Whether the contractAddress field is set.
     */
    public boolean hasContractAddress() {
      return contractAddress_ != null;
    }
    /**
     * <code>.aelf.Address contract_address = 1;</code>
     * @return The contractAddress.
     */
    public aelf.Core.Address getContractAddress() {
      return contractAddress_ == null ? aelf.Core.Address.getDefaultInstance() : contractAddress_;
    }
    /**
     * <code>.aelf.Address contract_address = 1;</code>
     */
    public aelf.Core.AddressOrBuilder getContractAddressOrBuilder() {
      return getContractAddress();
    }

    public static final int OWNER_ADDRESS_FIELD_NUMBER = 2;
    private aelf.Core.Address ownerAddress_;
    /**
     * <code>.aelf.Address owner_address = 2;</code>
     * @return Whether the ownerAddress field is set.
     */
    public boolean hasOwnerAddress() {
      return ownerAddress_ != null;
    }
    /**
     * <code>.aelf.Address owner_address = 2;</code>
     * @return The ownerAddress.
     */
    public aelf.Core.Address getOwnerAddress() {
      return ownerAddress_ == null ? aelf.Core.Address.getDefaultInstance() : ownerAddress_;
    }
    /**
     * <code>.aelf.Address owner_address = 2;</code>
     */
    public aelf.Core.AddressOrBuilder getOwnerAddressOrBuilder() {
      return getOwnerAddress();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (contractAddress_ != null) {
        output.writeMessage(1, getContractAddress());
      }
      if (ownerAddress_ != null) {
        output.writeMessage(2, getOwnerAddress());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (contractAddress_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getContractAddress());
      }
      if (ownerAddress_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getOwnerAddress());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ca.AuthorityInfoOuterClass.AuthorityInfo)) {
        return super.equals(obj);
      }
      ca.AuthorityInfoOuterClass.AuthorityInfo other = (ca.AuthorityInfoOuterClass.AuthorityInfo) obj;

      if (hasContractAddress() != other.hasContractAddress()) return false;
      if (hasContractAddress()) {
        if (!getContractAddress()
            .equals(other.getContractAddress())) return false;
      }
      if (hasOwnerAddress() != other.hasOwnerAddress()) return false;
      if (hasOwnerAddress()) {
        if (!getOwnerAddress()
            .equals(other.getOwnerAddress())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasContractAddress()) {
        hash = (37 * hash) + CONTRACT_ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getContractAddress().hashCode();
      }
      if (hasOwnerAddress()) {
        hash = (37 * hash) + OWNER_ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getOwnerAddress().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ca.AuthorityInfoOuterClass.AuthorityInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.AuthorityInfoOuterClass.AuthorityInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.AuthorityInfoOuterClass.AuthorityInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.AuthorityInfoOuterClass.AuthorityInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.AuthorityInfoOuterClass.AuthorityInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ca.AuthorityInfoOuterClass.AuthorityInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ca.AuthorityInfoOuterClass.AuthorityInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.AuthorityInfoOuterClass.AuthorityInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.AuthorityInfoOuterClass.AuthorityInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ca.AuthorityInfoOuterClass.AuthorityInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ca.AuthorityInfoOuterClass.AuthorityInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ca.AuthorityInfoOuterClass.AuthorityInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ca.AuthorityInfoOuterClass.AuthorityInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ca.AuthorityInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ca.AuthorityInfo)
        ca.AuthorityInfoOuterClass.AuthorityInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ca.AuthorityInfoOuterClass.internal_static_ca_AuthorityInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ca.AuthorityInfoOuterClass.internal_static_ca_AuthorityInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ca.AuthorityInfoOuterClass.AuthorityInfo.class, ca.AuthorityInfoOuterClass.AuthorityInfo.Builder.class);
      }

      // Construct using ca.AuthorityInfoOuterClass.AuthorityInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (contractAddressBuilder_ == null) {
          contractAddress_ = null;
        } else {
          contractAddress_ = null;
          contractAddressBuilder_ = null;
        }
        if (ownerAddressBuilder_ == null) {
          ownerAddress_ = null;
        } else {
          ownerAddress_ = null;
          ownerAddressBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ca.AuthorityInfoOuterClass.internal_static_ca_AuthorityInfo_descriptor;
      }

      @java.lang.Override
      public ca.AuthorityInfoOuterClass.AuthorityInfo getDefaultInstanceForType() {
        return ca.AuthorityInfoOuterClass.AuthorityInfo.getDefaultInstance();
      }

      @java.lang.Override
      public ca.AuthorityInfoOuterClass.AuthorityInfo build() {
        ca.AuthorityInfoOuterClass.AuthorityInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ca.AuthorityInfoOuterClass.AuthorityInfo buildPartial() {
        ca.AuthorityInfoOuterClass.AuthorityInfo result = new ca.AuthorityInfoOuterClass.AuthorityInfo(this);
        if (contractAddressBuilder_ == null) {
          result.contractAddress_ = contractAddress_;
        } else {
          result.contractAddress_ = contractAddressBuilder_.build();
        }
        if (ownerAddressBuilder_ == null) {
          result.ownerAddress_ = ownerAddress_;
        } else {
          result.ownerAddress_ = ownerAddressBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ca.AuthorityInfoOuterClass.AuthorityInfo) {
          return mergeFrom((ca.AuthorityInfoOuterClass.AuthorityInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ca.AuthorityInfoOuterClass.AuthorityInfo other) {
        if (other == ca.AuthorityInfoOuterClass.AuthorityInfo.getDefaultInstance()) return this;
        if (other.hasContractAddress()) {
          mergeContractAddress(other.getContractAddress());
        }
        if (other.hasOwnerAddress()) {
          mergeOwnerAddress(other.getOwnerAddress());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ca.AuthorityInfoOuterClass.AuthorityInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ca.AuthorityInfoOuterClass.AuthorityInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private aelf.Core.Address contractAddress_;
      private com.google.protobuf.SingleFieldBuilderV3<
          aelf.Core.Address, aelf.Core.Address.Builder, aelf.Core.AddressOrBuilder> contractAddressBuilder_;
      /**
       * <code>.aelf.Address contract_address = 1;</code>
       * @return Whether the contractAddress field is set.
       */
      public boolean hasContractAddress() {
        return contractAddressBuilder_ != null || contractAddress_ != null;
      }
      /**
       * <code>.aelf.Address contract_address = 1;</code>
       * @return The contractAddress.
       */
      public aelf.Core.Address getContractAddress() {
        if (contractAddressBuilder_ == null) {
          return contractAddress_ == null ? aelf.Core.Address.getDefaultInstance() : contractAddress_;
        } else {
          return contractAddressBuilder_.getMessage();
        }
      }
      /**
       * <code>.aelf.Address contract_address = 1;</code>
       */
      public Builder setContractAddress(aelf.Core.Address value) {
        if (contractAddressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          contractAddress_ = value;
          onChanged();
        } else {
          contractAddressBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.aelf.Address contract_address = 1;</code>
       */
      public Builder setContractAddress(
          aelf.Core.Address.Builder builderForValue) {
        if (contractAddressBuilder_ == null) {
          contractAddress_ = builderForValue.build();
          onChanged();
        } else {
          contractAddressBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.aelf.Address contract_address = 1;</code>
       */
      public Builder mergeContractAddress(aelf.Core.Address value) {
        if (contractAddressBuilder_ == null) {
          if (contractAddress_ != null) {
            contractAddress_ =
              aelf.Core.Address.newBuilder(contractAddress_).mergeFrom(value).buildPartial();
          } else {
            contractAddress_ = value;
          }
          onChanged();
        } else {
          contractAddressBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.aelf.Address contract_address = 1;</code>
       */
      public Builder clearContractAddress() {
        if (contractAddressBuilder_ == null) {
          contractAddress_ = null;
          onChanged();
        } else {
          contractAddress_ = null;
          contractAddressBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.aelf.Address contract_address = 1;</code>
       */
      public aelf.Core.Address.Builder getContractAddressBuilder() {
        
        onChanged();
        return getContractAddressFieldBuilder().getBuilder();
      }
      /**
       * <code>.aelf.Address contract_address = 1;</code>
       */
      public aelf.Core.AddressOrBuilder getContractAddressOrBuilder() {
        if (contractAddressBuilder_ != null) {
          return contractAddressBuilder_.getMessageOrBuilder();
        } else {
          return contractAddress_ == null ?
              aelf.Core.Address.getDefaultInstance() : contractAddress_;
        }
      }
      /**
       * <code>.aelf.Address contract_address = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          aelf.Core.Address, aelf.Core.Address.Builder, aelf.Core.AddressOrBuilder> 
          getContractAddressFieldBuilder() {
        if (contractAddressBuilder_ == null) {
          contractAddressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              aelf.Core.Address, aelf.Core.Address.Builder, aelf.Core.AddressOrBuilder>(
                  getContractAddress(),
                  getParentForChildren(),
                  isClean());
          contractAddress_ = null;
        }
        return contractAddressBuilder_;
      }

      private aelf.Core.Address ownerAddress_;
      private com.google.protobuf.SingleFieldBuilderV3<
          aelf.Core.Address, aelf.Core.Address.Builder, aelf.Core.AddressOrBuilder> ownerAddressBuilder_;
      /**
       * <code>.aelf.Address owner_address = 2;</code>
       * @return Whether the ownerAddress field is set.
       */
      public boolean hasOwnerAddress() {
        return ownerAddressBuilder_ != null || ownerAddress_ != null;
      }
      /**
       * <code>.aelf.Address owner_address = 2;</code>
       * @return The ownerAddress.
       */
      public aelf.Core.Address getOwnerAddress() {
        if (ownerAddressBuilder_ == null) {
          return ownerAddress_ == null ? aelf.Core.Address.getDefaultInstance() : ownerAddress_;
        } else {
          return ownerAddressBuilder_.getMessage();
        }
      }
      /**
       * <code>.aelf.Address owner_address = 2;</code>
       */
      public Builder setOwnerAddress(aelf.Core.Address value) {
        if (ownerAddressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ownerAddress_ = value;
          onChanged();
        } else {
          ownerAddressBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.aelf.Address owner_address = 2;</code>
       */
      public Builder setOwnerAddress(
          aelf.Core.Address.Builder builderForValue) {
        if (ownerAddressBuilder_ == null) {
          ownerAddress_ = builderForValue.build();
          onChanged();
        } else {
          ownerAddressBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.aelf.Address owner_address = 2;</code>
       */
      public Builder mergeOwnerAddress(aelf.Core.Address value) {
        if (ownerAddressBuilder_ == null) {
          if (ownerAddress_ != null) {
            ownerAddress_ =
              aelf.Core.Address.newBuilder(ownerAddress_).mergeFrom(value).buildPartial();
          } else {
            ownerAddress_ = value;
          }
          onChanged();
        } else {
          ownerAddressBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.aelf.Address owner_address = 2;</code>
       */
      public Builder clearOwnerAddress() {
        if (ownerAddressBuilder_ == null) {
          ownerAddress_ = null;
          onChanged();
        } else {
          ownerAddress_ = null;
          ownerAddressBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.aelf.Address owner_address = 2;</code>
       */
      public aelf.Core.Address.Builder getOwnerAddressBuilder() {
        
        onChanged();
        return getOwnerAddressFieldBuilder().getBuilder();
      }
      /**
       * <code>.aelf.Address owner_address = 2;</code>
       */
      public aelf.Core.AddressOrBuilder getOwnerAddressOrBuilder() {
        if (ownerAddressBuilder_ != null) {
          return ownerAddressBuilder_.getMessageOrBuilder();
        } else {
          return ownerAddress_ == null ?
              aelf.Core.Address.getDefaultInstance() : ownerAddress_;
        }
      }
      /**
       * <code>.aelf.Address owner_address = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          aelf.Core.Address, aelf.Core.Address.Builder, aelf.Core.AddressOrBuilder> 
          getOwnerAddressFieldBuilder() {
        if (ownerAddressBuilder_ == null) {
          ownerAddressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              aelf.Core.Address, aelf.Core.Address.Builder, aelf.Core.AddressOrBuilder>(
                  getOwnerAddress(),
                  getParentForChildren(),
                  isClean());
          ownerAddress_ = null;
        }
        return ownerAddressBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ca.AuthorityInfo)
    }

    // @@protoc_insertion_point(class_scope:ca.AuthorityInfo)
    private static final ca.AuthorityInfoOuterClass.AuthorityInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ca.AuthorityInfoOuterClass.AuthorityInfo();
    }

    public static ca.AuthorityInfoOuterClass.AuthorityInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AuthorityInfo>
        PARSER = new com.google.protobuf.AbstractParser<AuthorityInfo>() {
      @java.lang.Override
      public AuthorityInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuthorityInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AuthorityInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuthorityInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ca.AuthorityInfoOuterClass.AuthorityInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ca_AuthorityInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ca_AuthorityInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024authority_info.proto\022\002ca\032\017aelf/core.pr" +
      "oto\"^\n\rAuthorityInfo\022\'\n\020contract_address" +
      "\030\001 \001(\0132\r.aelf.Address\022$\n\rowner_address\030\002" +
      " \001(\0132\r.aelf.Addressb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          aelf.Core.getDescriptor(),
        });
    internal_static_ca_AuthorityInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ca_AuthorityInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ca_AuthorityInfo_descriptor,
        new java.lang.String[] { "ContractAddress", "OwnerAddress", });
    aelf.Core.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
